export type Patient = {
    Id: string,
    BIRTHDATE: string,
    DEATHDATE: string,
    SSN: string,
    DRIVERS: string,
    PREFIX: string,
    FIRST: string,
    MIDDLE: string,
    LAST: string,
    SUFFIX: string,
    MAIDEN: string,
    MARITAL: string,
    RACE: string,
    ETHNICITY: string,
    GENDER: string,
    BIRTHPLACE: string,
    ADDRESS: string,
    CITY: string,
    STATE: string,
    COUNTY: string,
    FIPS: number,
    ZIP: number
}